### ISSUE TITLE
CME stack

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/CivModCore#49]
[04:25:49 ERROR]: Could not pass event InventoryClickEvent to CivModCore v1.7.9                                                                                                                                    
java.util.ConcurrentModificationException: null                                                                                                                                                                    
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_252]                                                                                                                               
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_252]                                                                                                                                  
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_252]                                                                                                                                  
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.updateInventory(ClickableInventory.java:191) ~[?:?]                                                                                           
        at vg.civcraft.mc.civmodcore.inventorygui.components.ComponableInventory.updateComponent(ComponableInventory.java:60) ~[?:?]                                                                               
        at vg.civcraft.mc.civmodcore.inventorygui.components.ComponableSection.updateComponent(ComponableSection.java:72) ~[?:?]                                                                                   
        at vg.civcraft.mc.civmodcore.inventorygui.components.InventoryComponent.update(InventoryComponent.java:42) ~[?:?]                                                                                          
        at vg.civcraft.mc.civmodcore.inventorygui.components.Scrollbar.lambda$getBackwardClick$0(Scrollbar.java:133) ~[?:?]                                                                                                at vg.civcraft.mc.civmodcore.inventorygui.LClickable.clicked(LClickable.java:44) ~[?:?]                                                                                                                    
        at vg.civcraft.mc.civmodcore.inventorygui.IClickable.onLeftClick(IClickable.java:56) ~[?:?]                                                                                                                        at vg.civcraft.mc.civmodcore.inventorygui.IClickable.handleClick(IClickable.java:111) ~[?:?]                                                                                                               
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.itemClick(ClickableInventory.java:160) ~[?:?]                                                                                                         at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventoryListener.inventoryClick(ClickableInventoryListener.java:28) ~[?:?]                                                                             
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor114.execute(Unknown Source) ~[?:?]                                                                                                   at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]                                                                                                     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]                                                                                          
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]                                                                                       
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[?:git-Paper-243]                                                                                                         
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]                                                        
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]                                                                                                           
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]                                                                             
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]                                                                                 
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]                                                                             
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]                                                                                         
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]                                                                                
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]                                                                              
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]                                                                               
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]                                                                                         
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by Protonull** [comment]
Do we know what plugin's GUI caused this?

**Comment by Maxopoly** [comment]
No idea

**Comment by Protonull** [comment]
Looking at the stack trace, the use of the `Scrollbar` component narrows it down. It's either FactoryMod or RealisticBiomes, as they are the only plugins, as of right now, that uses them. Since `LClickable`s are unfortunately based around lambdas, it'll require some more investigation.
