### ISSUE TITLE
CMC tab completion exception

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/CivModCore#76]
[14:32:47] [Server thread/ERROR]: Exception when P3O attempted to tab complete fm basic s
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/fm basic s' in plugin FactoryMod v2.5.1
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:1910) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1882) ~[patched_1.16.4.jar:git-Paper-355]
        at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.4.jar:git-Paper-355]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.4.jar:git-Paper-355]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.4.jar:git-Paper-355]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:636) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-355]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-355]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.Trie.complete(Trie.java:68) ~[?:?]
        at com.github.igotyou.FactoryMod.commands.FactoryTabCompleters.completeFactory(FactoryTabCompleters.java:21) ~[?:?]
        at com.github.igotyou.FactoryMod.commands.FactoryMenu.tabComplete(FactoryMenu.java:41) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.StandaloneCommandHandler.tabCompleteCommand(StandaloneCommandHandler.java:119) ~[?:?]
        at vg.civcraft.mc.civmodcore.ACivMod.onTabComplete(ACivMod.java:191) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.4.jar:git-Paper-355]
        ... 20 more

**Comment by okx-code** [comment]
This is Maxopoly's fault after he rejected my fix and wrote his own
I sent him a message three times about this and he ignored me

**Comment by wingzero54** [comment]
Fixed by #77
